import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    welcome: 'Welcome to BUWAD',
    selectLanguage: 'Select your language',
    english: 'English',
    tagalog: 'Tagalog',
    cebuano: 'Cebuano',
    systemTitle: 'Solar Fish Dryer',
    rainDetected: 'RAIN ALERT',
    enclosureSecured: 'COVER IS SAFE',
    environmentalData: 'CURRENT CONDITIONS',
    temperature: 'TEMPERATURE',
    humidity: 'HUMIDITY',
    sunlight: 'SUNLIGHT',
    rainSensor: 'RAIN SENSOR',
    systemState: 'DRYER STATUS',
    phase2ActiveFlipping: 'FLIPPING FISH',
    scheduler: 'TIMING',
    status: 'STATUS',
    nextFlip: 'NEXT FLIP',
    dryingParameters: 'FISH PROFILE',
    danggit: 'DANGGIT',
    bolinao: 'BOLINAO',
    rabbitfishThickFillet: 'Rabbitfish',
    anchoviesSmallMass: 'Anchovies',
    flipMechanism: 'FLIP MECHANISM',
    manualOverride: 'FLIP NOW',
    triggersImmediateFlip: 'Press to flip the fish immediately',
    flippingMode: 'FLIPPING MODE',
    environmentBased: 'ENVIRONMENT',
    timerBased: 'TIMER',
    sensorDriven: 'Sensor-driven',
    fixedInterval: 'Fixed cycle',
    executing: 'EXECUTING...',
    thickFillet: 'THICK FILLET',
    smallMass: 'SMALL MASS',
    sensorDrivenLabel: 'SENSOR-DRIVEN',
    fixedIntervalLabel: 'FIXED INTERVAL',
    profile: 'PROFILE',
    mode: 'MODE',
    cycle: 'CYCLE',
    adaptive: 'Adaptive',
    env: 'ENV',
    timer: 'TIMER',
    criticalNotifications: 'ALERTS',
    active: 'ACTIVE',
    dismiss: 'DISMISS',
    noActiveAlerts: 'NO ACTIVE ALERTS',
    allSystemsOperational: 'ALL SYSTEMS GOOD',
    resolved: 'RESOLVED',
    activityFeed: 'ACTIVITY LOG',
    entries: 'RECORDS',
    noActivityRecorded: 'NO ACTIVITY YET',
    systemEventsWillAppear: 'Events will show here',
    dashboard: 'HOME',
    controls: 'CONTROLS',
    alerts: 'ALERTS',
    logs: 'HISTORY',
    dismissedAlerts: 'DISMISSED ALERTS',
    systemReady: 'SYSTEM READY',
    allSystemsNominal: 'ALL SYSTEMS NOMINAL',
    dryingCycleStarted: 'DRYING CYCLE STARTED',
    phase2Active: 'PHASE 2 ACTIVE',
    noAdditionalDetails: 'No additional details available',
    manual: 'MANUAL',
    sensor: 'SENSOR',
    system: 'SYSTEM',
    all: 'ALL',
    high: 'HIGH',
    medium: 'MEDIUM',
    normal: 'NORMAL',
    info: 'INFO',
    rainProtocolActivated: 'RAIN PROTOCOL ACTIVE',
    moistureDetectedEnclosureSecured: 'Moisture detected - Enclosure secured',
    coverSafe: 'COVER SAFE',
    wet: 'WET',
    dry: 'DRY',
    systemOffline: 'SYSTEM OFFLINE',
    turnOnToStart: 'TURN ON TO START',
    poweredOff: 'POWERED OFF',
    nextAutoFlipIn: 'NEXT AUTO FLIP IN',
    awaitingData: 'AWAITING DATA',
    off: 'OFF',
    systemStatus: 'SYSTEM STATUS',
    power: 'POWER',
    on: 'ON',
    turnOff: 'TURN OFF',
    turnOn: 'TURN ON',
    demoMode: 'DEMO MODE',
    noSensorData: 'No sensor data available · Displaying sample values',
    switchedToDanggit: 'Switched to Danggit',
    switchedToBolinao: 'Switched to Bolinao',
    switchedToEnvironment: 'Switched to Environment-Based flipping',
    switchedToTimer: 'Switched to Timer-Based flipping',
    fishFlippedSuccessfully: 'Fish flipped successfully',
    notificationsEnabled: 'Notifications enabled',
    notificationsDisabled: 'Notifications disabled',
    notificationPermissionDenied: 'Notification permission denied',
    failedToInitializeNotifications: 'Failed to initialize notifications',
    notificationPermissionDismissed: 'Notification permission dismissed',
    enableInBrowserSettings: 'Enable in browser settings',
    rainDetectedLabel: 'RAIN DETECTED',
    noRainDetectedLabel: 'NO RAIN DETECTED',
    buwadTurnedOff: 'BUWAD IS TURNED OFF',
    coverIsOn: 'COVER IS ON',
    analytics: 'ANALYTICS',
    batchSummary: 'BATCH SUMMARY',
    exportCsv: 'EXPORT DATA (.CSV)',
    dryingEfficiency: 'SOLAR EFFICIENCY',
    thermalGain: 'HEAT RETENTION',
    sensorTrends: '24H SENSOR TRENDS',
    hardwareHealth: 'SYSTEM HEALTH',
    totalFlips: 'TOTAL FLIPS',
    timeSaved: 'TIME SAVED',
    moistureTarget: 'MOISTURE GOAL'
  },
  tl: {
    welcome: 'Maligayang pagdating sa BUWAD',
    selectLanguage: 'Piliin ang iyong wika',
    english: 'English',
    tagalog: 'Tagalog',
    cebuano: 'Cebuano',
    systemTitle: 'Solar Fish Dryer',
    rainDetected: 'ALERTS SA ULAN',
    enclosureSecured: 'LIGTAS ANG TAKIP',
    environmentalData: 'KASALUKUYANG KUNDISYON',
    temperature: 'TEMPERATURA',
    humidity: 'HUMIDIDAD',
    sunlight: 'SINAG NG ARAW',
    rainSensor: 'SENSOR NG ULAN',
    systemState: 'ESTADO NG PATUYO',
    phase2ActiveFlipping: 'BINIBALIKTAD ANG ISDA',
    scheduler: 'ORAS',
    status: 'ESTADO',
    nextFlip: 'SUSUNOD NA BALIKTAD',
    dryingParameters: 'PROFILE NG ISDA',
    danggit: 'DANGGIT',
    bolinao: 'BOLINAO',
    rabbitfishThickFillet: 'Rabbitfish',
    anchoviesSmallMass: 'Anchovies',
    flipMechanism: 'MEKANISMO NG PAGBALIKTAD',
    manualOverride: 'BALIKTARIN NGAYON',
    triggersImmediateFlip: 'Pindutin para baliktarin agad ang isda',
    flippingMode: 'PARAAN NG PAGBALIKTAD',
    environmentBased: 'KAPALIGIRAN',
    timerBased: 'ORASAN',
    sensorDriven: 'Batay sa sensor',
    fixedInterval: 'Nakatakdang ikot',
    executing: 'ISINASAGAWA...',
    thickFillet: 'MAKAPAL NA ISDA',
    smallMass: 'MALIIT NA ISDA',
    sensorDrivenLabel: 'SENSOR-DRIVEN',
    fixedIntervalLabel: 'NAKATAKDANG ORAS',
    profile: 'PROFILE',
    mode: 'MODE',
    cycle: 'IKOT',
    adaptive: 'Umaangkop',
    env: 'ENV',
    timer: 'TIMER',
    criticalNotifications: 'MGA ALERTS',
    active: 'AKTIBO',
    dismiss: 'TANGGALIN',
    noActiveAlerts: 'WALANG AKTIBONG ALERTS',
    allSystemsOperational: 'LAHAT NG SISTEMA AY MAAYOS',
    resolved: 'NAAYOS',
    activityFeed: 'TALA NG GAWAIN',
    entries: 'MGA TALA',
    noActivityRecorded: 'WALA PANG GAWAIN',
    systemEventsWillAppear: 'Lalabas dito ang mga pangyayari',
    dashboard: 'HOME',
    controls: 'KONTROL',
    alerts: 'MGA ALERTS',
    logs: 'KASAYSAYAN',
    dismissedAlerts: 'MGA TINANGGAL NA ALERTS',
    systemReady: 'HANDA NA ANG SISTEMA',
    allSystemsNominal: 'NORMAL ANG LAHAT NG SISTEMA',
    dryingCycleStarted: 'NASIMULAN NA ANG PAGPAPATUYO',
    phase2Active: 'YUGTO 2 AKTIBO',
    noAdditionalDetails: 'Walang karagdagang detalye',
    manual: 'MANWAL',
    sensor: 'SENSOR',
    system: 'SISTEMA',
    all: 'LAHAT',
    high: 'MATAAS',
    medium: 'KATAMTAMAN',
    normal: 'NORMAL',
    info: 'IMPORMASYON',
    rainProtocolActivated: 'PROTOKOL SA ULAN AKTIBO',
    moistureDetectedEnclosureSecured: 'May nakitang halumigmig - Ligtas ang takip',
    coverSafe: 'LIGTAS ANG TAKIP',
    wet: 'BASA',
    dry: 'TUYO',
    systemOffline: 'OFFLINE ANG SISTEMA',
    turnOnToStart: 'I-ON PARA MAG-UMPSA',
    poweredOff: 'NAKA-OFF',
    nextAutoFlipIn: 'SUSUNOD NA AUTO BALIKTAD',
    awaitingData: 'HINIHINTAY ANG DATA',
    off: 'OFF',
    systemStatus: 'ESTADO NG SISTEMA',
    power: 'POWER',
    on: 'ON',
    turnOff: 'I-OFF',
    turnOn: 'I-ON',
    demoMode: 'DEMO MODE',
    noSensorData: 'Walang sensor data · Nagpapakita ng halimbawa',
    switchedToDanggit: 'Pinalitan sa Danggit',
    switchedToBolinao: 'Pinalitan sa Bolinao',
    switchedToEnvironment: 'Pinalitan sa Environment-Based na pagbaliktad',
    switchedToTimer: 'Pinalitan sa Timer-Based na pagbaliktad',
    fishFlippedSuccessfully: 'Matagumpay na nabaliktad ang isda',
    notificationsEnabled: 'Naka-enable ang notifications',
    notificationsDisabled: 'Naka-disable ang notifications',
    notificationPermissionDenied: 'Tinanggihan ang pahintulot sa notification',
    failedToInitializeNotifications: 'Nabigong i-initialize ang notifications',
    notificationPermissionDismissed: 'Isinara ang pahintulot sa notification',
    enableInBrowserSettings: 'I-enable sa browser settings',
    rainDetectedLabel: 'MAY ULAN',
    noRainDetectedLabel: 'WALANG ULAN',
    buwadTurnedOff: 'NAKA-OFF ANG BUWAD',
    coverIsOn: 'NAKASARA ANG TAKIP',
    analytics: 'ANALITIKA',
    batchSummary: 'BUOD NG BATCH',
    exportCsv: 'I-EXPORT ANG DATA',
    dryingEfficiency: 'EPISYENSYA SA ARAW',
    thermalGain: 'PAGPAPANATILI NG INIT',
    sensorTrends: 'MGA TREND NG SENSOR',
    hardwareHealth: 'KALUSUGAN NG SISTEMA',
    totalFlips: 'KABUUANG BALIKTAD',
    timeSaved: 'NATIPID NA ORAS',
    moistureTarget: 'TARGET NA TUYO'
  },
  ceb: {
    welcome: 'Maayong pag-abot sa BUWAD',
    selectLanguage: 'Pilia ang imong pinulongan',
    english: 'English',
    tagalog: 'Tagalog',
    cebuano: 'Cebuano',
    systemTitle: 'Solar Fish Dryer',
    rainDetected: 'ALERTS SA ULAN',
    enclosureSecured: 'SEGURO ANG TABON',
    environmentalData: 'KARON NGA KUNDISYON',
    temperature: 'TEMPERATURA',
    humidity: 'KABASA',
    sunlight: 'KAINIT SA ADLAW',
    rainSensor: 'SENSOR SA ULAN',
    systemState: 'ESTADO SA PAGPA-UGA',
    phase2ActiveFlipping: 'GIBALI-BALI ANG ISDA',
    scheduler: 'ORAS',
    status: 'ESTADO',
    nextFlip: 'SUNOD NGA BALI',
    dryingParameters: 'PROFILE SA ISDA',
    danggit: 'DANGGIT',
    bolinao: 'BOLINAO',
    rabbitfishThickFillet: 'Rabbitfish',
    anchoviesSmallMass: 'Anchovies',
    flipMechanism: 'MEKANISMO SA PAGBALI',
    manualOverride: 'BALIHON KARON',
    triggersImmediateFlip: 'Pindota para balihon dayon ang isda',
    flippingMode: 'PAAGI SA PAGBALI',
    environmentBased: 'KALIKASAN',
    timerBased: 'ORASAN',
    sensorDriven: 'Base sa sensor',
    fixedInterval: 'Pirmi nga siklo',
    executing: 'GIPATUMAN...',
    thickFillet: 'BAGA NGA ISDA',
    smallMass: 'GAMAY NGA ISDA',
    sensorDrivenLabel: 'SENSOR-DRIVEN',
    fixedIntervalLabel: 'PIRMI NGA ORAS',
    profile: 'PROFILE',
    mode: 'MODE',
    cycle: 'SIKLO',
    adaptive: 'Mopahiangay',
    env: 'ENV',
    timer: 'TIMER',
    criticalNotifications: 'MGA PAHIBALO',
    active: 'AKTIBO',
    dismiss: 'TANGTANGON',
    noActiveAlerts: 'WALAY AKTIBONG PAHIBALO',
    allSystemsOperational: 'TANANG SISTEMA MAOYOS',
    resolved: 'NA-AYO NA',
    activityFeed: 'TALA SA KALIHOKAN',
    entries: 'MGA TALA',
    noActivityRecorded: 'WALA PAY KALIHOKAN',
    systemEventsWillAppear: 'Makita dinhi ang mga panghitabo',
    dashboard: 'HOME',
    controls: 'KONTROL',
    alerts: 'MGA PAHIBALO',
    logs: 'KASAYSAYAN',
    dismissedAlerts: 'MGA GITANGGAL NGA PAHIBALO',
    systemReady: 'ANDAM NA ANG SISTEMA',
    allSystemsNominal: 'NORMAL ANG TANANG SISTEMA',
    dryingCycleStarted: 'NISUGOD NA ANG PAGPA-UGA',
    phase2Active: 'YUGTO 2 AKTIBO',
    noAdditionalDetails: 'Walay dugang detalye',
    manual: 'MANWAL',
    sensor: 'SENSOR',
    system: 'SISTEMA',
    all: 'TANAN',
    high: 'TAAS',
    medium: 'KATAMTAMAN',
    normal: 'NORMAL',
    info: 'IMPORMASYON',
    rainProtocolActivated: 'PROTOKOL SA ULAN AKTIBO',
    moistureDetectedEnclosureSecured: 'Nakit-an ang basa - Seguro ang tabon',
    coverSafe: 'SEGURO ANG TABON',
    wet: 'BASA',
    dry: 'UGA',
    systemOffline: 'OFFLINE ANG SISTEMA',
    turnOnToStart: 'I-ON ARON MAGSUGOD',
    poweredOff: 'NAKA-OFF',
    nextAutoFlipIn: 'SUNOD NGA AUTO BALI',
    awaitingData: 'NAGHULAT SA DATA',
    off: 'OFF',
    systemStatus: 'ESTADO SA SISTEMA',
    power: 'POWER',
    on: 'ON',
    turnOff: 'I-OFF',
    turnOn: 'I-ON',
    demoMode: 'DEMO MODE',
    noSensorData: 'Walay sensor data · Nagpakita og sample',
    switchedToDanggit: 'Giusab sa Danggit',
    switchedToBolinao: 'Giusab sa Bolinao',
    switchedToEnvironment: 'Giusab sa Environment-Based nga pagbali',
    switchedToTimer: 'Giusab sa Timer-Based nga pagbali',
    fishFlippedSuccessfully: 'Malampusong nabali ang isda',
    notificationsEnabled: 'Naka-enable ang notifications',
    notificationsDisabled: 'Naka-disable ang notifications',
    notificationPermissionDenied: 'Gibaliwala ang pagtugot sa notification',
    failedToInitializeNotifications: 'Napakyas sa pag-initialize sa notifications',
    notificationPermissionDismissed: 'Gisirado ang pagtugot sa notification',
    enableInBrowserSettings: 'I-enable sa browser settings',
    rainDetectedLabel: 'MAY ULAN',
    noRainDetectedLabel: 'WALAY ULAN',
    buwadTurnedOff: 'NAKA-OFF ANG BUWAD',
    coverIsOn: 'SIRADO ANG TABON',
    analytics: 'ANALITIKA',
    batchSummary: 'SUMARYO SA BATCH',
    exportCsv: 'I-EXPORT ANG DATA',
    dryingEfficiency: 'KAEPEKTIBO SA ARAW',
    thermalGain: 'PAGPUGONG SA KAINIT',
    sensorTrends: 'MGA TREND SA SENSOR',
    hardwareHealth: 'KALIG-ON SA SISTEMA',
    totalFlips: 'KABUUANG BALI',
    timeSaved: 'NATIPID NGA ORAS',
    moistureTarget: 'TARGET NGA UGA'
  }
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');
  const [hasSelectedLanguage, setHasSelectedLanguage] = useState(false);
  const [onLanguageSelectedCallback, setOnLanguageSelectedCallback] = useState(null);

  useEffect(() => {
    const savedLang = localStorage.getItem('buwad_language');
    const savedPreference = localStorage.getItem('buwad_save_language');
    
    if (savedLang && savedPreference === 'true') {
      setLanguage(savedLang);
      setHasSelectedLanguage(true);
    }
  }, []);

  const t = (key) => {
    const translation = translations[language]?.[key];
    if (translation) return translation;
    return translations.en[key] || key;
  };

  const selectLanguage = (lang, save = false) => {
    setLanguage(lang);
    setHasSelectedLanguage(true);
    
    if (save) {
      localStorage.setItem('buwad_language', lang);
      localStorage.setItem('buwad_save_language', 'true');
    } else {
      localStorage.removeItem('buwad_language');
      localStorage.removeItem('buwad_save_language');
    }
    
    if (onLanguageSelectedCallback) {
      onLanguageSelectedCallback();
    }
  };

  const resetLanguage = () => {
    setHasSelectedLanguage(false);
    setLanguage('en');
    localStorage.removeItem('buwad_language');
    localStorage.removeItem('buwad_save_language');
  };

  const registerLanguageCallback = (callback) => {
    setOnLanguageSelectedCallback(() => callback);
  };

  return (
    <LanguageContext.Provider value={{ 
      language, 
      t, 
      selectLanguage, 
      hasSelectedLanguage, 
      resetLanguage,
      registerLanguageCallback
    }}>
      {children}
    </LanguageContext.Provider>
  );
};