import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    welcome: 'Welcome to BUWAD',
    selectLanguage: 'Select your language',
    english: 'English',
    tagalog: 'Tagalog',
    cebuano: 'Cebuano',
    systemTitle: 'Solar Fish Dryer',
    rainDetected: 'RAIN ALERT',
    enclosureSecured: 'COVER IS SAFE',
    environmentalData: 'CURRENT CONDITIONS',
    temperature: 'TEMPERATURE',
    humidity: 'HUMIDITY',
    sunlight: 'SUNLIGHT',
    rainSensor: 'RAIN SENSOR',
    systemState: 'DRYER STATUS',
    phase2ActiveFlipping: 'FLIPPING FISH',
    scheduler: 'TIMING',
    status: 'STATUS',
    nextFlip: 'NEXT FLIP',
    dryingParameters: 'FISH PROFILE',
    danggit: 'DANGGIT',
    bolinao: 'BOLINAO',
    rabbitfishThickFillet: 'Rabbitfish',
    anchoviesSmallMass: 'Anchovies',
    flipMechanism: 'FLIP MECHANISM',
    manualOverride: 'FLIP NOW',
    triggersImmediateFlip: 'Press to flip the fish immediately',
    flippingMode: 'FLIPPING MODE',
    environmentBased: 'ENVIRONMENT',
    timerBased: 'TIMER',
    sensorDriven: 'Sensor-driven',
    fixedInterval: 'Fixed cycle',
    executing: 'EXECUTING...',
    thickFillet: 'THICK FILLET',
    smallMass: 'SMALL MASS',
    sensorDrivenLabel: 'SENSOR-DRIVEN',
    fixedIntervalLabel: 'FIXED INTERVAL',
    profile: 'PROFILE',
    mode: 'MODE',
    cycle: 'CYCLE',
    adaptive: 'Adaptive',
    env: 'ENV',
    timer: 'TIMER',
    criticalNotifications: 'ALERTS',
    active: 'ACTIVE',
    dismiss: 'DISMISS',
    noActiveAlerts: 'NO ACTIVE ALERTS',
    allSystemsOperational: 'ALL SYSTEMS GOOD',
    resolved: 'RESOLVED',
    activityFeed: 'ACTIVITY LOG',
    entries: 'RECORDS',
    noActivityRecorded: 'NO ACTIVITY YET',
    systemEventsWillAppear: 'Events will show here',
    dashboard: 'HOME',
    controls: 'CONTROLS',
    alerts: 'ALERTS',
    logs: 'HISTORY',
    dismissedAlerts: 'DISMISSED ALERTS',
    systemReady: 'SYSTEM READY',
    allSystemsNominal: 'ALL SYSTEMS NOMINAL',
    dryingCycleStarted: 'DRYING CYCLE STARTED',
    phase2Active: 'PHASE 2 ACTIVE',
    noAdditionalDetails: 'No additional details available',
    manual: 'MANUAL',
    sensor: 'SENSOR',
    system: 'SYSTEM',
    all: 'ALL',
    high: 'HIGH',
    medium: 'MEDIUM',
    normal: 'NORMAL',
    info: 'INFO',
    rainProtocolActivated: 'RAIN PROTOCOL ACTIVE',
    moistureDetectedEnclosureSecured: 'Moisture detected - Enclosure secured',
    coverSafe: 'COVER SAFE',
    wet: 'WET',
    dry: 'DRY',
    systemOffline: 'SYSTEM OFFLINE',
    turnOnToStart: 'TURN ON TO START',
    poweredOff: 'POWERED OFF',
    nextAutoFlipIn: 'NEXT AUTO FLIP IN',
    awaitingData: 'AWAITING DATA',
    off: 'OFF',
    systemStatus: 'SYSTEM STATUS',
    power: 'POWER',
    on: 'ON',
    turnOff: 'TURN OFF',
    turnOn: 'TURN ON',
    demoMode: 'DEMO MODE',
    noSensorData: 'No sensor data available · Displaying sample values',
    switchedToDanggit: 'Switched to Danggit',
    switchedToBolinao: 'Switched to Bolinao',
    switchedToEnvironment: 'Switched to Environment-Based flipping',
    switchedToTimer: 'Switched to Timer-Based flipping',
    fishFlippedSuccessfully: 'Fish flipped successfully',
    notificationsEnabled: 'Notifications enabled',
    notificationsDisabled: 'Notifications disabled',
    notificationPermissionDenied: 'Notification permission denied',
    failedToInitializeNotifications: 'Failed to initialize notifications',
    notificationPermissionDismissed: 'Notification permission dismissed',
    enableInBrowserSettings: 'Enable in browser settings'
  },
  tl: {
    welcome: 'Maligayang pagdating sa BUWAD',
    selectLanguage: 'Piliin ang iyong wika',
    english: 'English',
    tagalog: 'Tagalog',
    cebuano: 'Cebuano',
    systemTitle: 'Solar Fish Dryer',
    rainDetected: 'ALERTS SA ULAN',
    enclosureSecured: 'LIGTAS ANG TAKIP',
    environmentalData: 'KASALUKUYANG KUNDISYON',
    temperature: 'TEMPERATURA',
    humidity: 'HUMIDIDAD',
    sunlight: 'SINAG NG ARAW',
    rainSensor: 'SENSOR NG ULAN',
    systemState: 'ESTADO NG PATUYO',
    phase2ActiveFlipping: 'BINIBALIKTAD ANG ISDA',
    scheduler: 'ORAS',
    status: 'ESTADO',
    nextFlip: 'SUSUNOD NA BALIKTAD',
    dryingParameters: 'PROFILE NG ISDA',
    danggit: 'DANGGIT',
    bolinao: 'BOLINAO',
    rabbitfishThickFillet: 'Rabbitfish',
    anchoviesSmallMass: 'Anchovies',
    flipMechanism: 'MEKANISMO NG PAGBALIKTAD',
    manualOverride: 'BALIKTARIN NGAYON',
    triggersImmediateFlip: 'Pindutin para baliktarin agad ang isda',
    flippingMode: 'PARAAN NG PAGBALIKTAD',
    environmentBased: 'KAPALIGIRAN',
    timerBased: 'ORASAN',
    sensorDriven: 'Batay sa sensor',
    fixedInterval: 'Nakatakdang ikot',
    executing: 'ISINASAGAWA...',
    thickFillet: 'MAKAPAL NA ISDA',
    smallMass: 'MALIIT NA ISDA',
    sensorDrivenLabel: 'SENSOR-DRIVEN',
    fixedIntervalLabel: 'NAKATAKDANG ORAS',
    profile: 'PROFILE',
    mode: 'MODE',
    cycle: 'IKOT',
    adaptive: 'Umaangkop',
    env: 'ENV',
    timer: 'TIMER',
    criticalNotifications: 'MGA ALERTS',
    active: 'AKTIBO',
    dismiss: 'TANGGALIN',
    noActiveAlerts: 'WALANG AKTIBONG ALERTS',
    allSystemsOperational: 'LAHAT NG SISTEMA AY MAAYOS',
    resolved: 'NAAYOS',
    activityFeed: 'TALA NG GAWAIN',
    entries: 'MGA TALA',
    noActivityRecorded: 'WALA PANG GAWAIN',
    systemEventsWillAppear: 'Lalabas dito ang mga pangyayari',
    dashboard: 'HOME',
    controls: 'KONTROL',
    alerts: 'MGA ALERTS',
    logs: 'KASAYSAYAN',
    dismissedAlerts: 'MGA TINANGGAL NA ALERTS',
    systemReady: 'HANDA NA ANG SISTEMA',
    allSystemsNominal: 'NORMAL ANG LAHAT NG SISTEMA',
    dryingCycleStarted: 'NASIMULAN NA ANG PAGPAPATUYO',
    phase2Active: 'YUGTO 2 AKTIBO',
    noAdditionalDetails: 'Walang karagdagang detalye',
    manual: 'MANWAL',
    sensor: 'SENSOR',
    system: 'SISTEMA',
    all: 'LAHAT',
    high: 'MATAAS',
    medium: 'KATAMTAMAN',
    normal: 'NORMAL',
    info: 'IMPORMASYON',
    rainProtocolActivated: 'PROTOKOL SA ULAN AKTIBO',
    moistureDetectedEnclosureSecured: 'May nakitang halumigmig - Ligtas ang takip',
    coverSafe: 'LIGTAS ANG TAKIP',
    wet: 'BASA',
    dry: 'TUYO',
    systemOffline: 'OFFLINE ANG SISTEMA',
    turnOnToStart: 'I-ON PARA MAG-UMPSA',
    poweredOff: 'NAKA-OFF',
    nextAutoFlipIn: 'SUSUNOD NA AUTO BALIKTAD',
    awaitingData: 'HINIHINTAY ANG DATA',
    off: 'OFF',
    systemStatus: 'ESTADO NG SISTEMA',
    power: 'POWER',
    on: 'ON',
    turnOff: 'I-OFF',
    turnOn: 'I-ON',
    demoMode: 'DEMO MODE',
    noSensorData: 'Walang sensor data · Nagpapakita ng halimbawa',
    switchedToDanggit: 'Pinalitan sa Danggit',
    switchedToBolinao: 'Pinalitan sa Bolinao',
    switchedToEnvironment: 'Pinalitan sa Environment-Based na pagbaliktad',
    switchedToTimer: 'Pinalitan sa Timer-Based na pagbaliktad',
    fishFlippedSuccessfully: 'Matagumpay na nabaliktad ang isda',
    notificationsEnabled: 'Naka-enable ang notifications',
    notificationsDisabled: 'Naka-disable ang notifications',
    notificationPermissionDenied: 'Tinanggihan ang pahintulot sa notification',
    failedToInitializeNotifications: 'Nabigong i-initialize ang notifications',
    notificationPermissionDismissed: 'Isinara ang pahintulot sa notification',
    enableInBrowserSettings: 'I-enable sa browser settings'
  },
  ceb: {
    welcome: 'Maayong pag-abot sa BUWAD',
    selectLanguage: 'Pilia ang imong pinulongan',
    english: 'English',
    tagalog: 'Tagalog',
    cebuano: 'Cebuano',
    systemTitle: 'Solar Fish Dryer',
    rainDetected: 'ALERTS SA ULAN',
    enclosureSecured: 'SEGURO ANG TABON',
    environmentalData: 'KARON NGA KUNDISYON',
    temperature: 'TEMPERATURA',
    humidity: 'KABASA',
    sunlight: 'KAINIT SA ADLAW',
    rainSensor: 'SENSOR SA ULAN',
    systemState: 'ESTADO SA PAGPA-UGA',
    phase2ActiveFlipping: 'GIBALI-BALI ANG ISDA',
    scheduler: 'ORAS',
    status: 'ESTADO',
    nextFlip: 'SUNOD NGA BALI',
    dryingParameters: 'PROFILE SA ISDA',
    danggit: 'DANGGIT',
    bolinao: 'BOLINAO',
    rabbitfishThickFillet: 'Rabbitfish',
    anchoviesSmallMass: 'Anchovies',
    flipMechanism: 'MEKANISMO SA PAGBALI',
    manualOverride: 'BALIHON KARON',
    triggersImmediateFlip: 'Pindota para balihon dayon ang isda',
    flippingMode: 'PAAGI SA PAGBALI',
    environmentBased: 'KALIKASAN',
    timerBased: 'ORASAN',
    sensorDriven: 'Base sa sensor',
    fixedInterval: 'Pirmi nga siklo',
    executing: 'GIPATUMAN...',
    thickFillet: 'BAGA NGA ISDA',
    smallMass: 'GAMAY NGA ISDA',
    sensorDrivenLabel: 'SENSOR-DRIVEN',
    fixedIntervalLabel: 'PIRMI NGA ORAS',
    profile: 'PROFILE',
    mode: 'MODE',
    cycle: 'SIKLO',
    adaptive: 'Mopahiangay',
    env: 'ENV',
    timer: 'TIMER',
    criticalNotifications: 'MGA PAHIBALO',
    active: 'AKTIBO',
    dismiss: 'TANGTANGON',
    noActiveAlerts: 'WALAY AKTIBONG PAHIBALO',
    allSystemsOperational: 'TANANG SISTEMA MAOYOS',
    resolved: 'NA-AYO NA',
    activityFeed: 'TALA SA KALIHOKAN',
    entries: 'MGA TALA',
    noActivityRecorded: 'WALA PAY KALIHOKAN',
    systemEventsWillAppear: 'Makita dinhi ang mga panghitabo',
    dashboard: 'HOME',
    controls: 'KONTROL',
    alerts: 'MGA PAHIBALO',
    logs: 'KASAYSAYAN',
    dismissedAlerts: 'MGA GITANGGAL NGA PAHIBALO',
    systemReady: 'ANDAM NA ANG SISTEMA',
    allSystemsNominal: 'NORMAL ANG TANANG SISTEMA',
    dryingCycleStarted: 'NISUGOD NA ANG PAGPA-UGA',
    phase2Active: 'YUGTO 2 AKTIBO',
    noAdditionalDetails: 'Walay dugang detalye',
    manual: 'MANWAL',
    sensor: 'SENSOR',
    system: 'SISTEMA',
    all: 'TANAN',
    high: 'TAAS',
    medium: 'KATAMTAMAN',
    normal: 'NORMAL',
    info: 'IMPORMASYON',
    rainProtocolActivated: 'PROTOKOL SA ULAN AKTIBO',
    moistureDetectedEnclosureSecured: 'Nakit-an ang basa - Seguro ang tabon',
    coverSafe: 'SEGURO ANG TABON',
    wet: 'BASA',
    dry: 'UGA',
    systemOffline: 'OFFLINE ANG SISTEMA',
    turnOnToStart: 'I-ON ARON MAGSUGOD',
    poweredOff: 'NAKA-OFF',
    nextAutoFlipIn: 'SUNOD NGA AUTO BALI',
    awaitingData: 'NAGHULAT SA DATA',
    off: 'OFF',
    systemStatus: 'ESTADO SA SISTEMA',
    power: 'POWER',
    on: 'ON',
    turnOff: 'I-OFF',
    turnOn: 'I-ON',
    demoMode: 'DEMO MODE',
    noSensorData: 'Walay sensor data · Nagpakita og sample',
    switchedToDanggit: 'Giusab sa Danggit',
    switchedToBolinao: 'Giusab sa Bolinao',
    switchedToEnvironment: 'Giusab sa Environment-Based nga pagbali',
    switchedToTimer: 'Giusab sa Timer-Based nga pagbali',
    fishFlippedSuccessfully: 'Malampusong nabali ang isda',
    notificationsEnabled: 'Naka-enable ang notifications',
    notificationsDisabled: 'Naka-disable ang notifications',
    notificationPermissionDenied: 'Gibaliwala ang pagtugot sa notification',
    failedToInitializeNotifications: 'Napakyas sa pag-initialize sa notifications',
    notificationPermissionDismissed: 'Gisirado ang pagtugot sa notification',
    enableInBrowserSettings: 'I-enable sa browser settings'
  },
  es: {
    welcome: 'Bienvenido a BUWAD',
    selectLanguage: 'Selecciona tu idioma',
    english: 'Inglés',
    tagalog: 'Tagalo',
    cebuano: 'Cebuano',
    systemTitle: 'Secador Solar de Pescado',
    rainDetected: 'ALERTA DE LLUVIA',
    enclosureSecured: 'CUBIERTA SEGURA',
    environmentalData: 'CONDICIONES ACTUALES',
    temperature: 'TEMPERATURA',
    humidity: 'HUMEDAD',
    sunlight: 'LUZ SOLAR',
    rainSensor: 'SENSOR DE LLUVIA',
    systemState: 'ESTADO DEL SECADOR',
    phase2ActiveFlipping: 'VOLTEANDO PESCADO',
    scheduler: 'TIEMPO',
    status: 'ESTADO',
    nextFlip: 'PRÓXIMO VOLTEO',
    dryingParameters: 'PERFIL DE PESCADO',
    danggit: 'DANGGIT',
    bolinao: 'BOLINAO',
    rabbitfishThickFillet: 'Rabbitfish',
    anchoviesSmallMass: 'Anchovies',
    flipMechanism: 'MECANISMO DE VOLTEO',
    manualOverride: 'VOLTEAR AHORA',
    triggersImmediateFlip: 'Presiona para voltear el pescado',
    flippingMode: 'MODO DE VOLTEO',
    environmentBased: 'AMBIENTE',
    timerBased: 'TEMPORIZADOR',
    sensorDriven: 'Por sensor',
    fixedInterval: 'Ciclo fijo',
    executing: 'EJECUTANDO...',
    thickFillet: 'FILETE GRUESO',
    smallMass: 'MASA PEQUEÑA',
    sensorDrivenLabel: 'POR SENSOR',
    fixedIntervalLabel: 'INTERVALO FIJO',
    profile: 'PERFIL',
    mode: 'MODO',
    cycle: 'CICLO',
    adaptive: 'Adaptable',
    env: 'AMB',
    timer: 'TEMP',
    criticalNotifications: 'ALERTAS',
    active: 'ACTIVO',
    dismiss: 'DESCARTAR',
    noActiveAlerts: 'SIN ALERTAS ACTIVAS',
    allSystemsOperational: 'TODO FUNCIONA BIEN',
    resolved: 'RESUELTO',
    activityFeed: 'REGISTRO DE ACTIVIDAD',
    entries: 'REGISTROS',
    noActivityRecorded: 'SIN ACTIVIDAD',
    systemEventsWillAppear: 'Los eventos aparecerán aquí',
    dashboard: 'INICIO',
    controls: 'CONTROLES',
    alerts: 'ALERTAS',
    logs: 'HISTORIAL',
    dismissedAlerts: 'ALERTAS DESCARTADAS',
    systemReady: 'SISTEMA LISTO',
    allSystemsNominal: 'TODO NOMINAL',
    dryingCycleStarted: 'CICLO DE SECADO INICIADO',
    phase2Active: 'FASE 2 ACTIVA',
    noAdditionalDetails: 'Sin detalles adicionales',
    manual: 'MANUAL',
    sensor: 'SENSOR',
    system: 'SISTEMA',
    all: 'TODO',
    high: 'ALTO',
    medium: 'MEDIO',
    normal: 'NORMAL',
    info: 'INFO',
    rainProtocolActivated: 'PROTOCOLO DE LLUVIA ACTIVO',
    moistureDetectedEnclosureSecured: 'Humedad detectada - Cubierta segura',
    coverSafe: 'CUBIERTA SEGURA',
    wet: 'MOJADO',
    dry: 'SECO',
    systemOffline: 'SISTEMA FUERA DE LÍNEA',
    turnOnToStart: 'ENCENDER PARA INICIAR',
    poweredOff: 'APAGADO',
    nextAutoFlipIn: 'PRÓXIMO VOLTEO AUTO',
    awaitingData: 'ESPERANDO DATOS',
    off: 'OFF',
    systemStatus: 'ESTADO DEL SISTEMA',
    power: 'ENERGÍA',
    on: 'ON',
    turnOff: 'APAGAR',
    turnOn: 'ENCENDER',
    demoMode: 'MODO DEMO',
    noSensorData: 'Sin datos del sensor · Mostrando valores de muestra',
    switchedToDanggit: 'Cambiado a Danggit',
    switchedToBolinao: 'Cambiado a Bolinao',
    switchedToEnvironment: 'Cambiado a volteo por ambiente',
    switchedToTimer: 'Cambiado a volteo por temporizador',
    fishFlippedSuccessfully: 'Pescado volteado exitosamente',
    notificationsEnabled: 'Notificaciones activadas',
    notificationsDisabled: 'Notificaciones desactivadas',
    notificationPermissionDenied: 'Permiso de notificación denegado',
    failedToInitializeNotifications: 'Error al inicializar notificaciones',
    notificationPermissionDismissed: 'Permiso de notificación descartado',
    enableInBrowserSettings: 'Activar en configuración del navegador'
  },
  fr: {
    welcome: 'Bienvenue à BUWAD',
    selectLanguage: 'Choisissez votre langue',
    english: 'Anglais',
    tagalog: 'Tagalog',
    cebuano: 'Cebuano',
    systemTitle: 'Séchoir Solaire à Poisson',
    rainDetected: 'ALERTE PLUIE',
    enclosureSecured: 'COUVERCLE SÉCURISÉ',
    environmentalData: 'CONDITIONS ACTUELLES',
    temperature: 'TEMPÉRATURE',
    humidity: 'HUMIDITÉ',
    sunlight: 'LUMIÈRE SOLAIRE',
    rainSensor: 'CAPTEUR DE PLUIE',
    systemState: 'ÉTAT DU SÉCHOIR',
    phase2ActiveFlipping: 'RETOURNEMENT DU POISSON',
    scheduler: 'MINUTERIE',
    status: 'STATUT',
    nextFlip: 'PROCHAIN RETOURNEMENT',
    dryingParameters: 'PROFIL DE POISSON',
    danggit: 'DANGGIT',
    bolinao: 'BOLINAO',
    rabbitfishThickFillet: 'Rabbitfish',
    anchoviesSmallMass: 'Anchovies',
    flipMechanism: 'MÉCANISME DE RETOURNEMENT',
    manualOverride: 'RETOURNER MAINTENANT',
    triggersImmediateFlip: 'Appuyez pour retourner le poisson',
    flippingMode: 'MODE DE RETOURNEMENT',
    environmentBased: 'ENVIRONNEMENT',
    timerBased: 'MINUTERIE',
    sensorDriven: 'Par capteur',
    fixedInterval: 'Cycle fixe',
    executing: 'EXÉCUTION...',
    thickFillet: 'FILET ÉPAIS',
    smallMass: 'PETITE MASSE',
    sensorDrivenLabel: 'PAR CAPTEUR',
    fixedIntervalLabel: 'INTERVALLE FIXE',
    profile: 'PROFIL',
    mode: 'MODE',
    cycle: 'CYCLE',
    adaptive: 'Adaptatif',
    env: 'ENV',
    timer: 'MIN',
    criticalNotifications: 'ALERTES',
    active: 'ACTIF',
    dismiss: 'IGNORER',
    noActiveAlerts: 'AUCUNE ALERTE ACTIVE',
    allSystemsOperational: 'TOUT FONCTIONNE',
    resolved: 'RÉSOLU',
    activityFeed: 'JOURNAL D\'ACTIVITÉ',
    entries: 'ENTRÉES',
    noActivityRecorded: 'AUCUNE ACTIVITÉ',
    systemEventsWillAppear: 'Les événements apparaîtront ici',
    dashboard: 'ACCUEIL',
    controls: 'COMMANDES',
    alerts: 'ALERTES',
    logs: 'HISTORIQUE',
    dismissedAlerts: 'ALERTES IGNORÉES',
    systemReady: 'SYSTÈME PRÊT',
    allSystemsNominal: 'TOUT NOMINAL',
    dryingCycleStarted: 'CYCLE DE SÉCHAGE DÉMARRÉ',
    phase2Active: 'PHASE 2 ACTIVE',
    noAdditionalDetails: 'Aucun détail supplémentaire',
    manual: 'MANUEL',
    sensor: 'CAPTEUR',
    system: 'SYSTÈME',
    all: 'TOUT',
    high: 'ÉLEVÉ',
    medium: 'MOYEN',
    normal: 'NORMAL',
    info: 'INFO',
    rainProtocolActivated: 'PROTOCOLE PLUIE ACTIF',
    moistureDetectedEnclosureSecured: 'Humidité détectée - Couvercle sécurisé',
    coverSafe: 'COUVERCLE SÉCURISÉ',
    wet: 'MOUILLÉ',
    dry: 'SEC',
    systemOffline: 'SYSTÈME HORS LIGNE',
    turnOnToStart: 'ALLUMER POUR DÉMARRER',
    poweredOff: 'ÉTEINT',
    nextAutoFlipIn: 'PROCHAIN RETOURNEMENT AUTO',
    awaitingData: 'EN ATTENTE DE DONNÉES',
    off: 'OFF',
    systemStatus: 'ÉTAT DU SYSTÈME',
    power: 'ALIMENTATION',
    on: 'ON',
    turnOff: 'ÉTEINDRE',
    turnOn: 'ALLUMER',
    demoMode: 'MODE DÉMO',
    noSensorData: 'Aucune donnée capteur · Affichage d\'exemples',
    switchedToDanggit: 'Basculé sur Danggit',
    switchedToBolinao: 'Basculé sur Bolinao',
    switchedToEnvironment: 'Basculé sur retournement environnemental',
    switchedToTimer: 'Basculé sur retournement minuté',
    fishFlippedSuccessfully: 'Poisson retourné avec succès',
    notificationsEnabled: 'Notifications activées',
    notificationsDisabled: 'Notifications désactivées',
    notificationPermissionDenied: 'Permission de notification refusée',
    failedToInitializeNotifications: 'Échec d\'initialisation des notifications',
    notificationPermissionDismissed: 'Permission de notification ignorée',
    enableInBrowserSettings: 'Activer dans les paramètres du navigateur'
  },
  de: {
    welcome: 'Willkommen bei BUWAD',
    selectLanguage: 'Wählen Sie Ihre Sprache',
    english: 'Englisch',
    tagalog: 'Tagalog',
    cebuano: 'Cebuano',
    systemTitle: 'Solarer Fischtrockner',
    rainDetected: 'REGENALARM',
    enclosureSecured: 'ABDECKUNG SICHER',
    environmentalData: 'AKTUELLE BEDINGUNGEN',
    temperature: 'TEMPERATUR',
    humidity: 'LUFTFEUCHTIGKEIT',
    sunlight: 'SONNENLICHT',
    rainSensor: 'REGENSENSOR',
    systemState: 'TROCKNERSTATUS',
    phase2ActiveFlipping: 'FISCH WIRD GEWENDET',
    scheduler: 'ZEITGEBER',
    status: 'STATUS',
    nextFlip: 'NÄCHSTES WENDEN',
    dryingParameters: 'FISCHPROFIL',
    danggit: 'DANGGIT',
    bolinao: 'BOLINAO',
    rabbitfishThickFillet: 'Rabbitfish',
    anchoviesSmallMass: 'Anchovies',
    flipMechanism: 'WENDEMECHANISMUS',
    manualOverride: 'JETZT WENDEN',
    triggersImmediateFlip: 'Drücken zum sofortigen Wenden',
    flippingMode: 'WENDEMODUS',
    environmentBased: 'UMGEBUNG',
    timerBased: 'TIMER',
    sensorDriven: 'Sensorgesteuert',
    fixedInterval: 'Fester Zyklus',
    executing: 'AUSFÜHREN...',
    thickFillet: 'DICKES FILET',
    smallMass: 'KLEINE MASSE',
    sensorDrivenLabel: 'SENSORGESTEUERT',
    fixedIntervalLabel: 'FESTER INTERVALL',
    profile: 'PROFIL',
    mode: 'MODUS',
    cycle: 'ZYKLUS',
    adaptive: 'Adaptiv',
    env: 'UMG',
    timer: 'TIMER',
    criticalNotifications: 'ALARME',
    active: 'AKTIV',
    dismiss: 'SCHLIESSEN',
    noActiveAlerts: 'KEINE AKTIVEN ALARME',
    allSystemsOperational: 'ALLE SYSTEME FUNKTIONIEREN',
    resolved: 'ERLEDIGT',
    activityFeed: 'AKTIVITÄTSPROTOKOLL',
    entries: 'EINTRÄGE',
    noActivityRecorded: 'KEINE AKTIVITÄT',
    systemEventsWillAppear: 'Ereignisse erscheinen hier',
    dashboard: 'STARTSEITE',
    controls: 'STEUERUNG',
    alerts: 'ALARME',
    logs: 'VERLAUF',
    dismissedAlerts: 'GESCHLOSSENE ALARME',
    systemReady: 'SYSTEM BEREIT',
    allSystemsNominal: 'ALLES NOMINAL',
    dryingCycleStarted: 'TROCKNUNGSZYKLUS GESTARTET',
    phase2Active: 'PHASE 2 AKTIV',
    noAdditionalDetails: 'Keine weiteren Details',
    manual: 'MANUELL',
    sensor: 'SENSOR',
    system: 'SYSTEM',
    all: 'ALLE',
    high: 'HOCH',
    medium: 'MITTEL',
    normal: 'NORMAL',
    info: 'INFO',
    rainProtocolActivated: 'REGENPROTOKOLL AKTIV',
    moistureDetectedEnclosureSecured: 'Feuchtigkeit erkannt - Abdeckung sicher',
    coverSafe: 'ABDECKUNG SICHER',
    wet: 'NASS',
    dry: 'TROCKEN',
    systemOffline: 'SYSTEM OFFLINE',
    turnOnToStart: 'EINSCHALTEN ZUM STARTEN',
    poweredOff: 'AUSGESCHALTET',
    nextAutoFlipIn: 'NÄCHSTES AUTO-WENDEN',
    awaitingData: 'WARTE AUF DATEN',
    off: 'AUS',
    systemStatus: 'SYSTEMSTATUS',
    power: 'STROM',
    on: 'EIN',
    turnOff: 'AUSSCHALTEN',
    turnOn: 'EINSCHALTEN',
    demoMode: 'DEMO-MODUS',
    noSensorData: 'Keine Sensordaten · Beispielwerte werden angezeigt',
    switchedToDanggit: 'Zu Danggit gewechselt',
    switchedToBolinao: 'Zu Bolinao gewechselt',
    switchedToEnvironment: 'Zu umgebungsbasiertem Wenden gewechselt',
    switchedToTimer: 'Zu zeitbasiertem Wenden gewechselt',
    fishFlippedSuccessfully: 'Fisch erfolgreich gewendet',
    notificationsEnabled: 'Benachrichtigungen aktiviert',
    notificationsDisabled: 'Benachrichtigungen deaktiviert',
    notificationPermissionDenied: 'Benachrichtigungsberechtigung verweigert',
    failedToInitializeNotifications: 'Initialisierung der Benachrichtigungen fehlgeschlagen',
    notificationPermissionDismissed: 'Benachrichtigungsberechtigung geschlossen',
    enableInBrowserSettings: 'In Browsereinstellungen aktivieren'
  },
  it: {
    welcome: 'Benvenuto su BUWAD',
    selectLanguage: 'Seleziona la tua lingua',
    english: 'Inglese',
    tagalog: 'Tagalog',
    cebuano: 'Cebuano',
    systemTitle: 'Essiccatore Solare per Pesce',
    rainDetected: 'ALLERTA PIOGGIA',
    enclosureSecured: 'COPERCHIO SICURO',
    environmentalData: 'CONDIZIONI ATTUALI',
    temperature: 'TEMPERATURA',
    humidity: 'UMIDITÀ',
    sunlight: 'LUCE SOLARE',
    rainSensor: 'SENSORE PIOGGIA',
    systemState: 'STATO ESSICCATORE',
    phase2ActiveFlipping: 'GIRANDO IL PESCE',
    scheduler: 'TIMER',
    status: 'STATO',
    nextFlip: 'PROSSIMO GIRO',
    dryingParameters: 'PROFILO PESCE',
    danggit: 'DANGGIT',
    bolinao: 'BOLINAO',
    rabbitfishThickFillet: 'Rabbitfish',
    anchoviesSmallMass: 'Anchovies',
    flipMechanism: 'MECCANISMO DI GIRATURA',
    manualOverride: 'GIRA ORA',
    triggersImmediateFlip: 'Premi per girare il pesce',
    flippingMode: 'MODALITÀ DI GIRATURA',
    environmentBased: 'AMBIENTE',
    timerBased: 'TIMER',
    sensorDriven: 'Guidato da sensori',
    fixedInterval: 'Ciclo fisso',
    executing: 'ESECUZIONE...',
    thickFillet: 'FILETTO SPESSO',
    smallMass: 'MASSA PICCOLA',
    sensorDrivenLabel: 'GUIDATO DA SENSORI',
    fixedIntervalLabel: 'INTERVALLO FISSO',
    profile: 'PROFILO',
    mode: 'MODALITÀ',
    cycle: 'CICLO',
    adaptive: 'Adattivo',
    env: 'AMB',
    timer: 'TIMER',
    criticalNotifications: 'ALLERTE',
    active: 'ATTIVO',
    dismiss: 'IGNORA',
    noActiveAlerts: 'NESSUN ALLERTA ATTIVO',
    allSystemsOperational: 'TUTTO FUNZIONA',
    resolved: 'RISOLTO',
    activityFeed: 'REGISTRO ATTIVITÀ',
    entries: 'REGISTRAZIONI',
    noActivityRecorded: 'NESSUNA ATTIVITÀ',
    systemEventsWillAppear: 'Gli eventi appariranno qui',
    dashboard: 'HOME',
    controls: 'CONTROLLI',
    alerts: 'ALLERTE',
    logs: 'CRONOLOGIA',
    dismissedAlerts: 'ALLERTE IGNORATE',
    systemReady: 'SISTEMA PRONTO',
    allSystemsNominal: 'TUTTO NOMINALE',
    dryingCycleStarted: 'CICLO DI ESSICCAZIONE AVVIATO',
    phase2Active: 'FASE 2 ATTIVA',
    noAdditionalDetails: 'Nessun dettaglio aggiuntivo',
    manual: 'MANUALE',
    sensor: 'SENSORE',
    system: 'SISTEMA',
    all: 'TUTTO',
    high: 'ALTO',
    medium: 'MEDIO',
    normal: 'NORMALE',
    info: 'INFO',
    rainProtocolActivated: 'PROTOCOLLO PIOGGIA ATTIVO',
    moistureDetectedEnclosureSecured: 'Umidità rilevata - Coperchio sicuro',
    coverSafe: 'COPERCHIO SICURO',
    wet: 'BAGNATO',
    dry: 'ASCIUTTO',
    systemOffline: 'SISTEMA OFFLINE',
    turnOnToStart: 'ACCENDI PER INIZIARE',
    poweredOff: 'SPENTO',
    nextAutoFlipIn: 'PROSSIMO GIRO AUTO',
    awaitingData: 'IN ATTESA DI DATI',
    off: 'OFF',
    systemStatus: 'STATO SISTEMA',
    power: 'ALIMENTAZIONE',
    on: 'ON',
    turnOff: 'SPEGNI',
    turnOn: 'ACCENDI',
    demoMode: 'MODALITÀ DEMO',
    noSensorData: 'Nessun dato sensore · Visualizzazione valori campione',
    switchedToDanggit: 'Passato a Danggit',
    switchedToBolinao: 'Passato a Bolinao',
    switchedToEnvironment: 'Passato a giratura ambientale',
    switchedToTimer: 'Passato a giratura temporizzata',
    fishFlippedSuccessfully: 'Pesce girato con successo',
    notificationsEnabled: 'Notifiche attivate',
    notificationsDisabled: 'Notifiche disattivate',
    notificationPermissionDenied: 'Permesso notifiche negato',
    failedToInitializeNotifications: 'Inizializzazione notifiche fallita',
    notificationPermissionDismissed: 'Permesso notifiche ignorato',
    enableInBrowserSettings: 'Attiva nelle impostazioni del browser'
  },
  pt: {
    welcome: 'Bem-vindo ao BUWAD',
    selectLanguage: 'Selecione seu idioma',
    english: 'Inglês',
    tagalog: 'Tagalo',
    cebuano: 'Cebuano',
    systemTitle: 'Secador Solar de Peixe',
    rainDetected: 'ALERTA DE CHUVA',
    enclosureSecured: 'COBERTURA SEGURA',
    environmentalData: 'CONDIÇÕES ATUAIS',
    temperature: 'TEMPERATURA',
    humidity: 'UMIDADE',
    sunlight: 'LUZ SOLAR',
    rainSensor: 'SENSOR DE CHUVA',
    systemState: 'ESTADO DO SECADOR',
    phase2ActiveFlipping: 'VIRANDO O PEIXE',
    scheduler: 'TEMPORIZADOR',
    status: 'ESTADO',
    nextFlip: 'PRÓXIMA VIRADA',
    dryingParameters: 'PERFIL DO PEIXE',
    danggit: 'DANGGIT',
    bolinao: 'BOLINAO',
    rabbitfishThickFillet: 'Rabbitfish',
    anchoviesSmallMass: 'Anchovies',
    flipMechanism: 'MECANISMO DE VIRADA',
    manualOverride: 'VIRAR AGORA',
    triggersImmediateFlip: 'Pressione para virar o peixe',
    flippingMode: 'MODO DE VIRADA',
    environmentBased: 'AMBIENTE',
    timerBased: 'TEMPORIZADOR',
    sensorDriven: 'Por sensor',
    fixedInterval: 'Ciclo fixo',
    executing: 'EXECUTANDO...',
    thickFillet: 'FILÉ GROSSO',
    smallMass: 'MASSA PEQUENA',
    sensorDrivenLabel: 'POR SENSOR',
    fixedIntervalLabel: 'INTERVALO FIXO',
    profile: 'PERFIL',
    mode: 'MODO',
    cycle: 'CICLO',
    adaptive: 'Adaptativo',
    env: 'AMB',
    timer: 'TEMP',
    criticalNotifications: 'ALERTAS',
    active: 'ATIVO',
    dismiss: 'DISPENSAR',
    noActiveAlerts: 'NENHUM ALERTA ATIVO',
    allSystemsOperational: 'TUDO FUNCIONANDO',
    resolved: 'RESOLVIDO',
    activityFeed: 'REGISTRO DE ATIVIDADE',
    entries: 'REGISTROS',
    noActivityRecorded: 'NENHUMA ATIVIDADE',
    systemEventsWillAppear: 'Eventos aparecerão aqui',
    dashboard: 'INÍCIO',
    controls: 'CONTROLES',
    alerts: 'ALERTAS',
    logs: 'HISTÓRICO',
    dismissedAlerts: 'ALERTAS DISPENSADAS',
    systemReady: 'SISTEMA PRONTO',
    allSystemsNominal: 'TUDO NOMINAL',
    dryingCycleStarted: 'CICLO DE SECAGEM INICIADO',
    phase2Active: 'FASE 2 ATIVA',
    noAdditionalDetails: 'Sem detalhes adicionais',
    manual: 'MANUAL',
    sensor: 'SENSOR',
    system: 'SISTEMA',
    all: 'TODOS',
    high: 'ALTO',
    medium: 'MÉDIO',
    normal: 'NORMAL',
    info: 'INFO',
    rainProtocolActivated: 'PROTOCOLO DE CHUVA ATIVO',
    moistureDetectedEnclosureSecured: 'Umidade detectada - Cobertura segura',
    coverSafe: 'COBERTURA SEGURA',
    wet: 'MOLHADO',
    dry: 'SECO',
    systemOffline: 'SISTEMA OFFLINE',
    turnOnToStart: 'LIGAR PARA INICIAR',
    poweredOff: 'DESLIGADO',
    nextAutoFlipIn: 'PRÓXIMA VIRADA AUTO',
    awaitingData: 'AGUARDANDO DADOS',
    off: 'OFF',
    systemStatus: 'ESTADO DO SISTEMA',
    power: 'ENERGIA',
    on: 'ON',
    turnOff: 'DESLIGAR',
    turnOn: 'LIGAR',
    demoMode: 'MODO DEMO',
    noSensorData: 'Sem dados do sensor · Exibindo valores de exemplo',
    switchedToDanggit: 'Alterado para Danggit',
    switchedToBolinao: 'Alterado para Bolinao',
    switchedToEnvironment: 'Alterado para virada por ambiente',
    switchedToTimer: 'Alterado para virada por temporizador',
    fishFlippedSuccessfully: 'Peixe virado com sucesso',
    notificationsEnabled: 'Notificações ativadas',
    notificationsDisabled: 'Notificações desativadas',
    notificationPermissionDenied: 'Permissão de notificação negada',
    failedToInitializeNotifications: 'Falha ao inicializar notificações',
    notificationPermissionDismissed: 'Permissão de notificação descartada',
    enableInBrowserSettings: 'Ativar nas configurações do navegador'
  }
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');
  const [hasSelectedLanguage, setHasSelectedLanguage] = useState(false);
  const [onLanguageSelectedCallback, setOnLanguageSelectedCallback] = useState(null);

  useEffect(() => {
    const savedLang = localStorage.getItem('buwad_language');
    const savedPreference = localStorage.getItem('buwad_save_language');
    
    if (savedLang && savedPreference === 'true') {
      setLanguage(savedLang);
      setHasSelectedLanguage(true);
    }
  }, []);

  const t = (key) => {
    const translation = translations[language]?.[key];
    if (translation) return translation;
    return translations.en[key] || key;
  };

  const selectLanguage = (lang, save = false) => {
    setLanguage(lang);
    setHasSelectedLanguage(true);
    
    if (save) {
      localStorage.setItem('buwad_language', lang);
      localStorage.setItem('buwad_save_language', 'true');
    } else {
      localStorage.removeItem('buwad_language');
      localStorage.removeItem('buwad_save_language');
    }
    
    if (onLanguageSelectedCallback) {
      onLanguageSelectedCallback();
    }
  };

  const resetLanguage = () => {
    setHasSelectedLanguage(false);
    setLanguage('en');
    localStorage.removeItem('buwad_language');
    localStorage.removeItem('buwad_save_language');
  };

  const registerLanguageCallback = (callback) => {
    setOnLanguageSelectedCallback(() => callback);
  };

  return (
    <LanguageContext.Provider value={{ 
      language, 
      t, 
      selectLanguage, 
      hasSelectedLanguage, 
      resetLanguage,
      registerLanguageCallback
    }}>
      {children}
    </LanguageContext.Provider>
  );
};